name: Tests

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov
        pip install numpy scipy matplotlib seaborn pandas
        # Install headless PyTorch CPU version
        pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu
        # Install the package
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        if [ -f pyproject.toml ]; then pip install -e .; fi

    - name: Run fast CI tests
      env:
        # Set environment variable to use headless mode
        MPLBACKEND: Agg
        DISPLAY: ":99"
      run: |
        # Start virtual display for headless testing
        Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
        # Run fast tests only (excluding slow, integration, gpu tests)
        pytest -m "fast and not slow and not gpu" --cov=graphem_rapids --cov-report=xml --cov-report=html \
          --maxfail=0
        # Also run a quick smoke test of the examples
        cd examples && python quick_start_rapids.py || echo "Example test completed (may fail due to missing RAPIDS)"

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false